### ISSUE TITLE
Error when clicking / installation folder

### ISSUE THREAD

**Issue by Naruske** [ZachAR3/PineappleEA-GUI#14]
I've downloaded the files to E:\Games\Yuzu\Updater
My current installation folder for Yuzu is E:\Games\Yuzu\Yuzu

Error:opening GTK window failed: System.TypelnitializationException: The type initializer for DVGEK.Application' threw an exception. System.DllNotFoundException: Gtk: libgtk-3-0.dll. libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dl at GLibrary.Load (Library library) at Gtk.Application.cctor()
End of inner exception stack trace at Gtk.Application.Init() at Home.OpenFileChooser () in /mnt/Productivity/Gamemaking/Godot/Projects/YuzuEAU pdateManager/Scripts/Home.cs:line 461

**Comment by ZachAR3** [comment]
> I've downloaded the files to E:\Games\Yuzu\Updater My current installation folder for Yuzu is E:\Games\Yuzu\Yuzu
> 
> Error:opening GTK window failed: System.TypelnitializationException: The type initializer for DVGEK.Application' threw an exception. System.DllNotFoundException: Gtk: libgtk-3-0.dll. libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dl at GLibrary.Load (Library library) at Gtk.Application.cctor() End of inner exception stack trace at Gtk.Application.Init() at Home.OpenFileChooser () in /mnt/Productivity/Gamemaking/Godot/Projects/YuzuEAU pdateManager/Scripts/Home.cs:line 461

You need to install the GTK runtime as I stated under the release notes and in the readme. https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer

**Comment by ZachAR3** [comment]
Closing due to lack of response.
