### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by dracinn** [ZachAR3/PineappleEA-GUI#9]
Can we have the ability to manage the standard install as well?

**Comment by ZachAR3** [comment]
> Can we have the ability to manage the standard install as well?

It should be possible, but I would need to look into it, as it would have to pull the releases from the yuzu site since they don't post releases on github like pineapple does.

**Comment by dracinn** [comment]
I was simply interested in the idea to have one installer for each but it's a fair point as mainline has an installer and built-in updates.

**Comment by ZachAR3** [comment]
> I was simply interested in the idea to have one installer for each but it's a fair point as mainline has an installer and built-in updates.

No problem, just curious if that's something people would want since I don't wanna go through the effort of more webscraping if no one's gonna use it haha.

**Comment by ZachAR3** [comment]
Closed due to inactivity. May be reopened in the future if more interest is shown.
